### PR TITLE
Revert fixes for non-legacy data in scRNAseq (#17)

### PR DESCRIPTION
**Pull request by PeteHaitch**
Aaron made changes to **scRNAseq** after I filed issues regarding the points raised in #17.
So this PR:

1. Bumps the minimum version of **scRNAseq** so reflect these fixes.
2. Reverts most of the changes made in #17 (the change to `more-hvgs.Rmd` is still correct, so is not reverted).

The new minimal version of **scRNAseq** is not yet available from `BiocManager::install()` but should be in the next day or two.
@lgeistlinger you may not want to merge this PR until the new version becomes available.
Also, I have not bumped the version number of **OSCA.advanced**, so you will want to do that too before pushing to BioC's git.

### CODE REVIEW

**Comment by PeteHaitch** [comment]
@ltla Unfortunately the latest version of **scRNAseq** failed to build on BBS (https://bioconductor.org/checkResults/3.19/data-experiment-LATEST/scRNAseq/nebbiolo1-checksrc.html)

**Comment by lgeistlinger** [comment]
Thanks @PeteHaitch - just let me know once you'd like me to merge this one.

**Comment by PeteHaitch** [comment]
Good to merge now that **scRNAseq** v2.18.0 is available.
You'll need to bump the **OSCA.advanced** version.

**Comment by lgeistlinger** [comment]
Thanks Pete. Merging.

**Pull request merged**
